name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup Ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath $env:USERPROFILE\ngrok
          & "$env:USERPROFILE\ngrok\ngrok.exe" authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable RDP Access
        run: |
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          net user runneradmin YourPassword123!

      - name: Start Ngrok Tunnel
        run: |
          Start-Process "$env:USERPROFILE\ngrok\ngrok.exe" -ArgumentList "tcp", "3389" -WindowStyle Hidden

      - name: Show Connection Info
        run: |
          Start-Sleep -Seconds 15
          $tunnel = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $url = $tunnel.tunnels[0].public_url
          $cleanUrl = $url -replace "tcp://", ""
          Write-Output "`n*** RDP Connection Info ***"
          Write-Output "IP:Port => $cleanUrl"
          Write-Output "Username: runneradmin"
          Write-Output "Password: YourPassword123!"
