name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Get latest ngrok release URL
      id: get_url
      shell: pwsh
      run: |
        $release = Invoke-RestMethod -Uri "https://api.github.com/repos/ngrok/ngrok/releases/latest"
        $asset = $release.assets | Where-Object { $_.name -match "windows-amd64.zip" }
        echo "url=$($asset.browser_download_url)" >> $env:GITHUB_ENV

    - name: Download ngrok
      run: Invoke-WebRequest $env:url -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)

    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
