$retries = 0
$success = $false

# Start ngrok in the background
Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp", "3389"

# Retry until successful or maximum retries reached
do {
    Start-Sleep -Seconds 5
    try {
        $tunnel = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
        $success = $true
    } catch {
        $retries++
        Write-Host "Attempt $retries: Ngrok tunnel not yet available."
    }
} until ($success -or $retries -ge 20)  # Increased retry count to 20

# If unsuccessful, exit
if (-not $success) {
    Write-Host "Ngrok tunnel failed to start after 20 attempts."
    exit 1
}

# Extract the public URL from the tunnel and output it
$url = $tunnel.tunnels[0].public_url -replace "tcp://", ""
Write-Host "`n*** RDP Connection Info ***"
Write-Host "IP:Port => $url"
Write-Host "Username: runneradmin"
Write-Host "Password: YourPassword123!"
