name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download ngrok latest release
      run: |
        $url = "https://api.github.com/repos/ngrok/ngrok/releases/latest"
        $headers = @{ "Accept" = "application/vnd.github.v3+json" }
        $release = Invoke-RestMethod -Uri $url -Headers $headers
        $ngrokUrl = $release.assets | Where-Object { $_.name -match "windows-amd64.zip" } | Select-Object -ExpandProperty browser_download_url
        Invoke-WebRequest $ngrokUrl -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)

    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
